### ISSUE TITLE
details on evaluation

### ISSUE THREAD

**Issue by JupiterTop** [passing2961/DialogCC#1]
Hello,
When i read your paper, i am confused about the details on automatic evaluation of image retrieval: 

1. You said "set the the number of retrieval candidates to 100", there is randomness in the selection of both ground-truth images and candidates. Are the results in Table 12 the average results? If so, how many results are averaged?
2. Are all image-sharing turns in the test set involved in the evaluation?

Hope for your reply!
Best regards.

**Comment by passing2961** [comment]
Hello,

Sorry for too late response. 1. We fixed the seed number. So when we conducted the evaluation, we used the same candidates. 2. Yes, we considered all image-sharing turns in the evaluation.

**Comment by JupiterTop** [comment]
Thanks for your response.
